apiVersion: v1
kind: Pod
metadata:
  name: imagepullbackoff
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: registry.invalid/kubesage/not-found:missing
      imagePullPolicy: Always
