apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesage
  namespace: kubesage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesage-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "services", "endpoints", "nodes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesage-reader
subjects:
  - kind: ServiceAccount
    name: kubesage
    namespace: kubesage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesage-reader
