global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kubesage-host
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8080

  - job_name: kubesage-docker
    metrics_path: /metrics
    static_configs:
      - targets:
          - kubesage:8080
