CREATE DATABASE IF NOT EXISTS kubesage CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'kubesage'@'%' IDENTIFIED BY 'kubesage';
GRANT ALL PRIVILEGES ON kubesage.* TO 'kubesage'@'%';
FLUSH PRIVILEGES;
