apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesage.fullname" . }}
type: Opaque
stringData:
  mysql-password: {{ .Values.config.mysql.password | quote }}
  llm-api-key: {{ .Values.config.llm.apiKey | quote }}
  auth-token: {{ .Values.config.server.authToken | quote }}
  redis-password: {{ .Values.config.redis.password | quote }}
  redis-sentinel-password: {{ .Values.config.redis.sentinelPassword | quote }}
  rag-embedding-api-key: {{ .Values.config.rag.embedding.apiKey | quote }}
  qdrant-api-key: {{ .Values.config.rag.qdrant.apiKey | quote }}
  rag-pgvector-dsn: {{ .Values.config.rag.pgvector.dsn | quote }}
  slack-webhook-url: {{ .Values.config.notification.slackWebhookURL | quote }}
  feishu-webhook-url: {{ .Values.config.notification.feishuWebhookURL | quote }}
  dingtalk-webhook-url: {{ .Values.config.notification.dingTalkWebhookURL | quote }}
